from model.keypoint_classifier.keypoint_classifier import KeyPointClassifier
from model.point_history_classifier.point_history_classifier import PointHistoryClassifier
from model.handwritten_classifier.handwritten_classifier import HandwrittenClassifier
